### ISSUE TITLE
copyDriveFilesToUserLib

### ISSUE THREAD

**Issue by kemrop** [alexgurr/react-drive#3]
I see reference to 'api/copyDriveFilesToUserLib' I dont' see the lib folder? I am i missing something?

**Comment by kemrop** [comment]
Oops, I mean, am i missing the **api** folder?

**Comment by alexgurr** [comment]
Hey! Can you please let me know where the reference is? Thanks

**Comment by alexgurr** [comment]
Ah I see! This is just a code snippet example on how you could use the library. You need to provide your own implementation of what you do with the file/s (such as in the example for copying drive files)
